server:
  port: 8080
  servlet:
    context-path:

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=certificate_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: 1

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

